on: [pull_request, workflow_dispatch]
jobs:
  test:
    name: "Test the visualiser on ${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # macos-latest disabled due to the CI not catching that the tests on macOS finished…
    runs-on: ${{ matrix.os }}
    # timeout-minutes: 15  # Allow extra time for macOS
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          environment-file: "environment.yml"
          activate-environment: visualiser-env
      - name: Run Python tests
        shell: bash -l {0}
        run: python -m unittest
